export const navConfig = {
  main: [
    { name: "home", link: "/" },
    { name: "portfolio", link: "/portfolio" },
    { name: "about", link: "/about" },
    { name: "contact", link: "/contact" },
  ],
  portfolio: [
    { name: "experiments", link: "/portfoliolayout/experiments" },
    { name: "interactive SVGs", link: "/portfoliolayout/intSVGs" },
    { name: "prototypes", link: "/portfoliolayout/prototypes" },
    { name: "applications", link: "/portfoliolayout/applications" },
    { name: "games", link: "/portfoliolayout/games" },
    { name: "gen art", link: "/genart" },
  ],
  slides: [
    { name: "", imagelink: "./gen_art/let_it_flow.png" },
    { name: "", imagelink: "./gen_art/flow_field_3.13.2021.10.49.27.png" },
    { name: "", imagelink: "./gen_art/art_FF_lightning.png" },
    { name: "", imagelink: "./gen_art/art_everGreen_1.jpeg" },
    { name: "", imagelink: "./gen_art/art_everGreen_2.jpeg" },
    { name: "", imagelink: "./gen_art/art_everGreen_3.jpeg" },
    { name: "", imagelink: "./gen_art/art_everGreen_4.jpeg" },
    { name: "", imagelink: "./gen_art/art_everGreen_5.jpeg" },
    { name: "", imagelink: "./gen_art/art_everGreen_6.jpeg" },
    { name: "", imagelink: "./gen_art/art_fourier_1.jpeg" },
    { name: "", imagelink: "./gen_art/art_fourier_2.jpeg" },
    { name: "", imagelink: "./gen_art/art_fractal_trees_3.jpg" },
    { name: "", imagelink: "./gen_art/art_fractal_trees_4.jpeg" },
    { name: "", imagelink: "./gen_art/art_fractal_trees_5.jpeg" },
    { name: "", imagelink: "./gen_art/art_fractal_trees_pink.jpeg" },
    { name: "", imagelink: "./gen_art/art_fractal_trees.png" },
  ],
};
